import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { vehicles, type VehicleInsert } from './schema';
import 'dotenv/config';

const connectionString = process.env.DATABASE_URL || 'postgresql://localhost:5432/salesapexai';

// 30 vehicles with complete data for rehash calculator functionality
const sampleVehicles: VehicleInsert[] = [
  // Toyota (4 vehicles)
  {
    year: 2022,
    make: 'Toyota',
    model: 'Camry',
    trim: 'SE',
    price: 24995,
    mileage: 32000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Pearl White',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 28,
    mpgHighway: 39,
    features: ['Bluetooth', 'Backup Camera', 'Apple CarPlay', 'Lane Departure Warning', 'Keyless Entry'],
    description: 'Well-maintained Toyota Camry SE with excellent fuel economy. Clean title, one owner.',
    imageUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800',
    isAvailable: true,
  },
  {
    year: 2021,
    make: 'Toyota',
    model: 'RAV4',
    trim: 'XLE',
    price: 29500,
    mileage: 41000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Magnetic Gray',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 27,
    mpgHighway: 35,
    features: ['Sunroof', 'Heated Seats', 'Blind Spot Monitor', 'Power Liftgate', 'Navigation'],
    description: 'Popular RAV4 XLE AWD with sunroof and heated seats. Excellent condition.',
    imageUrl: 'https://images.unsplash.com/photo-1581540222194-0def2dda95b8?w=800',
    isAvailable: true,
  },
  {
    year: 2020,
    make: 'Toyota',
    model: 'Corolla',
    trim: 'LE',
    price: 17995,
    mileage: 48000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Classic Silver',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 30,
    mpgHighway: 38,
    features: ['Bluetooth', 'Backup Camera', 'USB Ports', 'Automatic Climate Control'],
    description: 'Reliable Toyota Corolla with excellent fuel economy. Perfect commuter car.',
    imageUrl: 'https://images.unsplash.com/photo-1623869675781-80aa31012a5a?w=800',
    isAvailable: true,
  },
  {
    year: 2019,
    make: 'Toyota',
    model: 'Tacoma',
    trim: 'SR5',
    price: 31995,
    mileage: 52000,
    bodyStyle: 'Truck',
    seats: 5,
    color: 'Barcelona Red',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: '4WD',
    mpgCity: 18,
    mpgHighway: 22,
    features: ['Tow Package', 'Bed Liner', 'Running Boards', 'Bluetooth', 'Backup Camera'],
    description: 'Rugged Tacoma SR5 4WD with tow package. Ready for work or adventure.',
    imageUrl: 'https://images.unsplash.com/photo-1605893477799-b99e3b8b93fe?w=800',
    isAvailable: true,
  },
  // Honda (4 vehicles)
  {
    year: 2022,
    make: 'Honda',
    model: 'Accord',
    trim: 'Sport',
    price: 26995,
    mileage: 28000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Crystal Black',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 26,
    mpgHighway: 34,
    features: ['Leather Seats', 'Sunroof', 'Honda Sensing', 'Wireless CarPlay', 'Premium Audio'],
    description: 'Sporty Honda Accord with leather interior and full Honda Sensing suite.',
    imageUrl: 'https://images.unsplash.com/photo-1606611013016-969c19ba27bb?w=800',
    isAvailable: true,
  },
  {
    year: 2021,
    make: 'Honda',
    model: 'CR-V',
    trim: 'EX-L',
    price: 28500,
    mileage: 39000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Obsidian Blue',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 27,
    mpgHighway: 32,
    features: ['Leather Seats', 'Heated Seats', 'Power Liftgate', 'Panoramic Sunroof'],
    description: 'Loaded CR-V EX-L AWD with premium features. Family-friendly SUV.',
    imageUrl: 'https://images.unsplash.com/photo-1568844293986-8c8a3e3bb50b?w=800',
    isAvailable: true,
  },
  {
    year: 2020,
    make: 'Honda',
    model: 'Civic',
    trim: 'LX',
    price: 17500,
    mileage: 51000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Lunar Silver',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 30,
    mpgHighway: 38,
    features: ['Bluetooth', 'Backup Camera', 'Automatic Headlights', 'USB Ports'],
    description: 'Economical Honda Civic with great reliability. Low cost of ownership.',
    imageUrl: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800',
    isAvailable: true,
  },
  {
    year: 2019,
    make: 'Honda',
    model: 'Pilot',
    trim: 'EX',
    price: 27995,
    mileage: 58000,
    bodyStyle: 'SUV',
    seats: 8,
    color: 'Modern Steel',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 19,
    mpgHighway: 26,
    features: ['Third Row', 'Apple CarPlay', 'Blind Spot Monitor', 'Rear Entertainment'],
    description: 'Spacious Honda Pilot EX with third-row seating. Perfect for large families.',
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
    isAvailable: true,
  },
  // Ford (4 vehicles)
  {
    year: 2021,
    make: 'Ford',
    model: 'F-150',
    trim: 'XLT',
    price: 39995,
    mileage: 38000,
    bodyStyle: 'Truck',
    seats: 6,
    color: 'Agate Black',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: '4WD',
    mpgCity: 18,
    mpgHighway: 24,
    features: ['Pro Trailer Backup Assist', 'SYNC 4', 'Bed Liner', 'Tow Package', '360 Camera'],
    description: 'Popular F-150 XLT with 4WD and full tow package. Work truck ready.',
    imageUrl: 'https://images.unsplash.com/photo-1605893477799-b99e3b8b93fe?w=800',
    isAvailable: true,
  },
  {
    year: 2022,
    make: 'Ford',
    model: 'Explorer',
    trim: 'XLT',
    price: 36500,
    mileage: 29000,
    bodyStyle: 'SUV',
    seats: 7,
    color: 'Oxford White',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 21,
    mpgHighway: 28,
    features: ['Third Row', 'SYNC 3', 'Co-Pilot360', 'Heated Seats', 'Power Liftgate'],
    description: 'Three-row Ford Explorer XLT with AWD. Great family SUV with towing capability.',
    imageUrl: 'https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800',
    isAvailable: true,
  },
  {
    year: 2020,
    make: 'Ford',
    model: 'Escape',
    trim: 'SE',
    price: 22995,
    mileage: 45000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Velocity Blue',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 27,
    mpgHighway: 33,
    features: ['Co-Pilot360', 'SYNC 3', 'Wireless Charging', 'Adaptive Cruise'],
    description: 'Efficient Ford Escape SE with modern tech. Great city SUV.',
    imageUrl: 'https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800',
    isAvailable: true,
  },
  {
    year: 2019,
    make: 'Ford',
    model: 'Mustang',
    trim: 'EcoBoost',
    price: 26995,
    mileage: 42000,
    bodyStyle: 'Coupe',
    seats: 4,
    color: 'Race Red',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'RWD',
    mpgCity: 21,
    mpgHighway: 31,
    features: ['Performance Package', 'SYNC 3', 'Backup Camera', 'Sport Suspension'],
    description: 'Iconic Ford Mustang EcoBoost with performance package. Head-turning style.',
    imageUrl: 'https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=800',
    isAvailable: true,
  },
  // Chevrolet (3 vehicles)
  {
    year: 2020,
    make: 'Chevrolet',
    model: 'Silverado 1500',
    trim: 'LT',
    price: 36995,
    mileage: 51000,
    bodyStyle: 'Truck',
    seats: 6,
    color: 'Summit White',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: '4WD',
    mpgCity: 16,
    mpgHighway: 22,
    features: ['Trailering Package', 'Bed Liner', 'Remote Start', 'Apple CarPlay', 'Z71 Package'],
    description: 'Capable Silverado LT with 4WD and Z71 off-road package. Work or play ready.',
    imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
    isAvailable: true,
  },
  {
    year: 2021,
    make: 'Chevrolet',
    model: 'Equinox',
    trim: 'LT',
    price: 23500,
    mileage: 44000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Satin Steel Gray',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 26,
    mpgHighway: 31,
    features: ['Heated Seats', 'Remote Start', 'Teen Driver', 'WiFi Hotspot', 'Safety Package'],
    description: 'Versatile Equinox AWD with convenient features. Great all-around SUV.',
    imageUrl: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800',
    isAvailable: true,
  },
  {
    year: 2019,
    make: 'Chevrolet',
    model: 'Malibu',
    trim: 'LT',
    price: 16500,
    mileage: 62000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Mosaic Black',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 27,
    mpgHighway: 36,
    features: ['Bluetooth', 'Backup Camera', 'Teen Driver', 'Apple CarPlay'],
    description: 'Affordable Malibu LT with spacious interior. Great value sedan.',
    imageUrl: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800',
    isAvailable: true,
  },
  // Hyundai/Kia (4 vehicles)
  {
    year: 2022,
    make: 'Hyundai',
    model: 'Tucson',
    trim: 'SEL',
    price: 27500,
    mileage: 26000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Amazon Gray',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 26,
    mpgHighway: 33,
    features: ['Blind Spot Monitor', 'Apple CarPlay', 'Lane Keep Assist', 'LED Headlights'],
    description: 'Stylish new-generation Tucson with modern safety features. 10-year warranty.',
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
    isAvailable: true,
  },
  {
    year: 2021,
    make: 'Hyundai',
    model: 'Sonata',
    trim: 'SEL',
    price: 22500,
    mileage: 39000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Phantom Black',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 28,
    mpgHighway: 38,
    features: ['Sunroof', 'Digital Key', 'Remote Smart Parking', 'Highway Driving Assist'],
    description: 'Feature-packed Sonata with advanced technology. Long warranty remaining.',
    imageUrl: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800',
    isAvailable: true,
  },
  {
    year: 2022,
    make: 'Kia',
    model: 'Sportage',
    trim: 'EX',
    price: 28995,
    mileage: 24000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Snow White Pearl',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 25,
    mpgHighway: 32,
    features: ['Dual Panoramic Displays', 'Heated Seats', 'Wireless CarPlay', 'Smart Cruise'],
    description: 'All-new Sportage with stunning dual screen display. Best warranty in class.',
    imageUrl: 'https://images.unsplash.com/photo-1606611013016-969c19ba27bb?w=800',
    isAvailable: true,
  },
  {
    year: 2021,
    make: 'Kia',
    model: 'Telluride',
    trim: 'LX',
    price: 36995,
    mileage: 35000,
    bodyStyle: 'SUV',
    seats: 8,
    color: 'Everlasting Silver',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 20,
    mpgHighway: 26,
    features: ['Third Row', 'Apple CarPlay', 'Forward Collision Warning', 'Lane Keep Assist'],
    description: 'Award-winning Telluride with three rows. Best-in-class family SUV.',
    imageUrl: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800',
    isAvailable: true,
  },
  // Nissan (2 vehicles)
  {
    year: 2021,
    make: 'Nissan',
    model: 'Altima',
    trim: 'SV',
    price: 21500,
    mileage: 48000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Gun Metallic',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 28,
    mpgHighway: 39,
    features: ['ProPILOT Assist', 'Remote Start', 'Heated Seats', 'Apple CarPlay'],
    description: 'Feature-rich Altima with ProPILOT Assist technology. Smooth ride.',
    imageUrl: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800',
    isAvailable: true,
  },
  {
    year: 2020,
    make: 'Nissan',
    model: 'Rogue',
    trim: 'SL',
    price: 24995,
    mileage: 55000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Pearl White Tricoat',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 25,
    mpgHighway: 32,
    features: ['Leather Seats', '360 Camera', 'Navigation', 'Bose Audio', 'ProPILOT'],
    description: 'Fully loaded Rogue SL with premium Bose audio and ProPILOT.',
    imageUrl: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800',
    isAvailable: true,
  },
  // Jeep/Dodge (3 vehicles)
  {
    year: 2021,
    make: 'Jeep',
    model: 'Grand Cherokee',
    trim: 'Laredo',
    price: 33500,
    mileage: 41000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Diamond Black',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: '4WD',
    mpgCity: 19,
    mpgHighway: 26,
    features: ['Uconnect 5', 'Trail Rated', 'Tow Package', 'Apple CarPlay', 'Blind Spot'],
    description: 'Capable Grand Cherokee with 4WD and tow package. On and off-road ready.',
    imageUrl: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800',
    isAvailable: true,
  },
  {
    year: 2022,
    make: 'Jeep',
    model: 'Wrangler',
    trim: 'Sport',
    price: 36500,
    mileage: 22000,
    bodyStyle: 'SUV',
    seats: 4,
    color: 'Firecracker Red',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: '4WD',
    mpgCity: 17,
    mpgHighway: 23,
    features: ['Removable Top', 'Trail Rated', 'Skid Plates', 'Rock Rails', 'Tow Hooks'],
    description: 'Iconic Wrangler Sport ready for adventure. Removable top for open-air fun.',
    imageUrl: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800',
    isAvailable: true,
  },
  {
    year: 2020,
    make: 'Dodge',
    model: 'Charger',
    trim: 'SXT',
    price: 25500,
    mileage: 49000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Pitch Black',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'RWD',
    mpgCity: 19,
    mpgHighway: 30,
    features: ['8.4" Touchscreen', 'Uconnect', 'Sport Suspension', 'Apple CarPlay'],
    description: 'Muscular Charger SXT with sport suspension. Bold American style.',
    imageUrl: 'https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=800',
    isAvailable: true,
  },
  // Subaru (2 vehicles)
  {
    year: 2022,
    make: 'Subaru',
    model: 'Outback',
    trim: 'Premium',
    price: 30995,
    mileage: 28000,
    bodyStyle: 'Wagon',
    seats: 5,
    color: 'Autumn Green',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 26,
    mpgHighway: 33,
    features: ['EyeSight', 'X-Mode', 'Starlink', 'Heated Seats', 'Roof Rails'],
    description: 'Adventure-ready Outback with EyeSight safety. Standard AWD.',
    imageUrl: 'https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800',
    isAvailable: true,
  },
  {
    year: 2021,
    make: 'Subaru',
    model: 'Forester',
    trim: 'Sport',
    price: 28500,
    mileage: 34000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Horizon Blue',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 26,
    mpgHighway: 33,
    features: ['Sport Suspension', 'SI-Drive', 'EyeSight', 'Panoramic Sunroof', 'X-Mode'],
    description: 'Sporty Forester with enhanced suspension. All-weather capability.',
    imageUrl: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800',
    isAvailable: true,
  },
  // Volkswagen (1 vehicle)
  {
    year: 2021,
    make: 'Volkswagen',
    model: 'Tiguan',
    trim: 'SE',
    price: 26500,
    mileage: 36000,
    bodyStyle: 'SUV',
    seats: 7,
    color: 'Pure White',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 21,
    mpgHighway: 29,
    features: ['Third Row', 'Panoramic Sunroof', 'Digital Cockpit', 'IQ.DRIVE'],
    description: 'Spacious Tiguan with optional third row. German engineering.',
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
    isAvailable: true,
  },
  // Mazda (1 vehicle)
  {
    year: 2022,
    make: 'Mazda',
    model: 'CX-5',
    trim: 'Touring',
    price: 27995,
    mileage: 23000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Soul Red Crystal',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 25,
    mpgHighway: 31,
    features: ['Leather Seats', 'Sunroof', 'Bose Audio', 'i-Activsense', 'Heated Seats'],
    description: 'Award-winning CX-5 with premium features. Best-in-class driving dynamics.',
    imageUrl: 'https://images.unsplash.com/photo-1619976215249-0ce0534e6c1f?w=800',
    isAvailable: true,
  },
  // Budget/Value (2 vehicles)
  {
    year: 2018,
    make: 'Toyota',
    model: 'Prius',
    trim: 'Two',
    price: 15995,
    mileage: 78000,
    bodyStyle: 'Hatchback',
    seats: 5,
    color: 'Sea Glass Pearl',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 54,
    mpgHighway: 50,
    features: ['Toyota Safety Sense', 'Backup Camera', 'Climate Control', 'Bluetooth'],
    description: 'Ultra-efficient Prius with amazing fuel economy. Hybrid savings.',
    imageUrl: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800',
    isAvailable: true,
  },
  {
    year: 2017,
    make: 'Honda',
    model: 'HR-V',
    trim: 'LX',
    price: 14995,
    mileage: 72000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Alabaster Silver',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 28,
    mpgHighway: 34,
    features: ['Bluetooth', 'Backup Camera', 'Magic Seat', 'USB Ports'],
    description: 'Compact HR-V with versatile Magic Seat. Budget-friendly SUV option.',
    imageUrl: 'https://images.unsplash.com/photo-1568844293986-8c8a3e3bb50b?w=800',
    isAvailable: true,
  },
];

async function seed() {
  const client = postgres(connectionString, { max: 1 });
  const db = drizzle(client);

  console.log('Seeding database...');

  // Clear existing vehicles
  await db.delete(vehicles);

  // Insert sample vehicles
  await db.insert(vehicles).values(sampleVehicles);

  console.log(`Inserted ${sampleVehicles.length} vehicles`);

  await client.end();
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seeding failed:', err);
  process.exit(1);
});
