import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { vehicles, type VehicleInsert } from './schema';
import 'dotenv/config';

const connectionString = process.env.DATABASE_URL || 'postgresql://localhost:5432/salesapexai';

const sampleVehicles: VehicleInsert[] = [
  // Toyota
  {
    year: 2022,
    make: 'Toyota',
    model: 'Camry',
    trim: 'SE',
    price: 26500,
    mileage: 28000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'White',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 28,
    mpgHighway: 39,
    features: ['Bluetooth', 'Backup Camera', 'Apple CarPlay', 'Lane Departure Warning', 'Keyless Entry'],
    description: 'Well-maintained Toyota Camry SE with low mileage. Clean title, one owner.',
    imageUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800',
    isAvailable: true,
  },
  {
    year: 2021,
    make: 'Toyota',
    model: 'RAV4',
    trim: 'XLE',
    price: 32000,
    mileage: 35000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Blue',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 27,
    mpgHighway: 35,
    features: ['Sunroof', 'Heated Seats', 'Blind Spot Monitor', 'Power Liftgate', 'Navigation'],
    description: 'Popular RAV4 XLE AWD with sunroof and heated seats.',
    imageUrl: 'https://images.unsplash.com/photo-1581540222194-0def2dda95b8?w=800',
    isAvailable: true,
  },
  {
    year: 2020,
    make: 'Toyota',
    model: 'Corolla',
    trim: 'LE',
    price: 19500,
    mileage: 42000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Silver',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 30,
    mpgHighway: 38,
    features: ['Bluetooth', 'Backup Camera', 'USB Ports', 'Automatic Climate Control'],
    description: 'Reliable Toyota Corolla with excellent fuel economy.',
    imageUrl: 'https://images.unsplash.com/photo-1623869675781-80aa31012a5a?w=800',
    isAvailable: true,
  },
  // Honda
  {
    year: 2022,
    make: 'Honda',
    model: 'Accord',
    trim: 'Sport',
    price: 28500,
    mileage: 22000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Black',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 26,
    mpgHighway: 34,
    features: ['Leather Seats', 'Sunroof', 'Honda Sensing', 'Wireless CarPlay', 'Premium Audio'],
    description: 'Sporty Honda Accord with leather interior and full Honda Sensing suite.',
    imageUrl: 'https://images.unsplash.com/photo-1606611013016-969c19ba27bb?w=800',
    isAvailable: true,
  },
  {
    year: 2021,
    make: 'Honda',
    model: 'CR-V',
    trim: 'EX-L',
    price: 31000,
    mileage: 38000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Red',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 27,
    mpgHighway: 32,
    features: ['Leather Seats', 'Heated Seats', 'Power Liftgate', 'Panoramic Sunroof'],
    description: 'Loaded CR-V EX-L AWD with premium features.',
    imageUrl: 'https://images.unsplash.com/photo-1568844293986-8c8a3e3bb50b?w=800',
    isAvailable: true,
  },
  {
    year: 2020,
    make: 'Honda',
    model: 'Civic',
    trim: 'LX',
    price: 18500,
    mileage: 45000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Gray',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 30,
    mpgHighway: 38,
    features: ['Bluetooth', 'Backup Camera', 'Automatic Headlights'],
    description: 'Economical Honda Civic with great reliability.',
    imageUrl: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800',
    isAvailable: true,
  },
  // Nissan
  {
    year: 2021,
    make: 'Nissan',
    model: 'Altima',
    trim: 'SV',
    price: 22000,
    mileage: 52000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'White',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 28,
    mpgHighway: 39,
    features: ['ProPILOT Assist', 'Remote Start', 'Heated Seats', 'Apple CarPlay'],
    description: 'Feature-rich Altima with ProPILOT Assist technology.',
    imageUrl: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800',
    isAvailable: true,
  },
  {
    year: 2019,
    make: 'Nissan',
    model: 'Rogue',
    trim: 'SL',
    price: 23500,
    mileage: 58000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Black',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 25,
    mpgHighway: 32,
    features: ['Leather Seats', '360 Camera', 'Navigation', 'Bose Audio'],
    description: 'Fully loaded Rogue SL with premium Bose audio.',
    imageUrl: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800',
    isAvailable: true,
  },
  // Ford
  {
    year: 2021,
    make: 'Ford',
    model: 'F-150',
    trim: 'XLT',
    price: 42000,
    mileage: 35000,
    bodyStyle: 'Truck',
    seats: 5,
    color: 'Blue',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: '4WD',
    mpgCity: 18,
    mpgHighway: 24,
    features: ['Pro Trailer Backup Assist', 'SYNC 4', 'Bed Liner', 'Tow Package'],
    description: 'Popular F-150 XLT with 4WD and tow package.',
    imageUrl: 'https://images.unsplash.com/photo-1605893477799-b99e3b8b93fe?w=800',
    isAvailable: true,
  },
  {
    year: 2022,
    make: 'Ford',
    model: 'Escape',
    trim: 'SE',
    price: 27500,
    mileage: 28000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Green',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 44,
    mpgHighway: 37,
    features: ['Co-Pilot360', 'SYNC 3', 'Wireless Charging', 'Adaptive Cruise'],
    description: 'Efficient Ford Escape Hybrid with excellent MPG.',
    imageUrl: 'https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800',
    isAvailable: true,
  },
  // Chevrolet
  {
    year: 2020,
    make: 'Chevrolet',
    model: 'Silverado 1500',
    trim: 'LT',
    price: 38000,
    mileage: 48000,
    bodyStyle: 'Truck',
    seats: 6,
    color: 'Red',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: '4WD',
    mpgCity: 16,
    mpgHighway: 22,
    features: ['Trailering Package', 'Bed Liner', 'Remote Start', 'Apple CarPlay'],
    description: 'Capable Silverado LT with 4WD and trailering package.',
    imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
    isAvailable: true,
  },
  {
    year: 2021,
    make: 'Chevrolet',
    model: 'Equinox',
    trim: 'LT',
    price: 25000,
    mileage: 42000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Silver',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 26,
    mpgHighway: 31,
    features: ['Heated Seats', 'Remote Start', 'Teen Driver', 'WiFi Hotspot'],
    description: 'Versatile Equinox AWD with convenient features.',
    imageUrl: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800',
    isAvailable: true,
  },
  // Hyundai
  {
    year: 2022,
    make: 'Hyundai',
    model: 'Tucson',
    trim: 'SEL',
    price: 28000,
    mileage: 25000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'White',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 26,
    mpgHighway: 33,
    features: ['Blind Spot Monitor', 'Apple CarPlay', 'Lane Keep Assist', 'LED Headlights'],
    description: 'Stylish new-generation Tucson with modern safety features.',
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
    isAvailable: true,
  },
  {
    year: 2021,
    make: 'Hyundai',
    model: 'Sonata',
    trim: 'SEL',
    price: 23500,
    mileage: 38000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Blue',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 28,
    mpgHighway: 38,
    features: ['Sunroof', 'Digital Key', 'Remote Smart Parking', 'Highway Driving Assist'],
    description: 'Feature-packed Sonata with advanced technology.',
    imageUrl: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800',
    isAvailable: true,
  },
  {
    year: 2019,
    make: 'Hyundai',
    model: 'Elantra',
    trim: 'SE',
    price: 14500,
    mileage: 65000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Gray',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 29,
    mpgHighway: 38,
    features: ['Bluetooth', 'Backup Camera', 'USB Ports'],
    description: 'Affordable Elantra with good remaining warranty.',
    imageUrl: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800',
    isAvailable: true,
  },
  // Kia
  {
    year: 2022,
    make: 'Kia',
    model: 'Sportage',
    trim: 'EX',
    price: 30000,
    mileage: 22000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Black',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 25,
    mpgHighway: 32,
    features: ['Dual Panoramic Displays', 'Heated Seats', 'Wireless CarPlay', 'Smart Cruise'],
    description: 'All-new Sportage with stunning dual screen display.',
    imageUrl: 'https://images.unsplash.com/photo-1606611013016-969c19ba27bb?w=800',
    isAvailable: true,
  },
  {
    year: 2021,
    make: 'Kia',
    model: 'Sorento',
    trim: 'LX',
    price: 29500,
    mileage: 35000,
    bodyStyle: 'SUV',
    seats: 7,
    color: 'White',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 24,
    mpgHighway: 29,
    features: ['Third Row', 'Apple CarPlay', 'Forward Collision Warning', 'Lane Keep Assist'],
    description: 'Three-row Sorento perfect for families.',
    imageUrl: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800',
    isAvailable: true,
  },
  // BMW
  {
    year: 2021,
    make: 'BMW',
    model: '3 Series',
    trim: '330i',
    price: 38500,
    mileage: 32000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Blue',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'RWD',
    mpgCity: 26,
    mpgHighway: 36,
    features: ['iDrive 7.0', 'Heated Seats', 'Parking Assistant', 'Live Cockpit Pro'],
    description: 'Sporty 330i with M Sport package styling.',
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
    isAvailable: true,
  },
  {
    year: 2020,
    make: 'BMW',
    model: 'X3',
    trim: 'xDrive30i',
    price: 36000,
    mileage: 42000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'White',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 23,
    mpgHighway: 29,
    features: ['Panoramic Sunroof', 'Navigation', 'Harman Kardon Audio', 'Heads-Up Display'],
    description: 'Luxury X3 with premium audio and heads-up display.',
    imageUrl: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800',
    isAvailable: true,
  },
  // Mercedes
  {
    year: 2021,
    make: 'Mercedes-Benz',
    model: 'C-Class',
    trim: 'C300',
    price: 40000,
    mileage: 28000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Silver',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'RWD',
    mpgCity: 23,
    mpgHighway: 33,
    features: ['MBUX', 'Burmester Audio', 'Panoramic Roof', 'LED Lighting'],
    description: 'Elegant C300 with premium Burmester audio.',
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
    isAvailable: true,
  },
  {
    year: 2020,
    make: 'Mercedes-Benz',
    model: 'GLC',
    trim: 'GLC300',
    price: 42000,
    mileage: 38000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Black',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 21,
    mpgHighway: 28,
    features: ['Navigation', 'Heated Seats', 'Power Liftgate', 'Premium Package'],
    description: 'Popular GLC300 4MATIC with Premium Package.',
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
    isAvailable: true,
  },
  // Mazda
  {
    year: 2022,
    make: 'Mazda',
    model: 'CX-5',
    trim: 'Touring',
    price: 29000,
    mileage: 20000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Red',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 25,
    mpgHighway: 31,
    features: ['Leather Seats', 'Sunroof', 'Bose Audio', 'i-Activsense'],
    description: 'Award-winning CX-5 with premium features.',
    imageUrl: 'https://images.unsplash.com/photo-1619976215249-0ce0534e6c1f?w=800',
    isAvailable: true,
  },
  {
    year: 2021,
    make: 'Mazda',
    model: 'Mazda3',
    trim: 'Premium',
    price: 24500,
    mileage: 32000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Gray',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 25,
    mpgHighway: 33,
    features: ['Leather Seats', 'Heads-Up Display', 'Bose Audio', 'Adaptive Cruise'],
    description: 'Premium Mazda3 AWD with luxurious interior.',
    imageUrl: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800',
    isAvailable: true,
  },
  // Subaru
  {
    year: 2022,
    make: 'Subaru',
    model: 'Outback',
    trim: 'Premium',
    price: 32500,
    mileage: 25000,
    bodyStyle: 'Wagon',
    seats: 5,
    color: 'Green',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 26,
    mpgHighway: 33,
    features: ['EyeSight', 'X-Mode', 'Starlink', 'Heated Seats'],
    description: 'Adventure-ready Outback with EyeSight safety.',
    imageUrl: 'https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800',
    isAvailable: true,
  },
  {
    year: 2021,
    make: 'Subaru',
    model: 'Forester',
    trim: 'Sport',
    price: 30000,
    mileage: 30000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Orange',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 26,
    mpgHighway: 33,
    features: ['Sport Suspension', 'SI-Drive', 'EyeSight', 'Panoramic Sunroof'],
    description: 'Sporty Forester with enhanced suspension.',
    imageUrl: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800',
    isAvailable: true,
  },
  // Dodge/Jeep
  {
    year: 2020,
    make: 'Dodge',
    model: 'Charger',
    trim: 'GT',
    price: 28000,
    mileage: 45000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Black',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'RWD',
    mpgCity: 19,
    mpgHighway: 30,
    features: ['8.4" Touchscreen', 'Performance Hood', 'Sport Suspension', 'Apple CarPlay'],
    description: 'Muscular Charger GT with sport suspension.',
    imageUrl: 'https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=800',
    isAvailable: true,
  },
  {
    year: 2021,
    make: 'Jeep',
    model: 'Grand Cherokee',
    trim: 'Laredo',
    price: 35000,
    mileage: 38000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Silver',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: '4WD',
    mpgCity: 19,
    mpgHighway: 26,
    features: ['Uconnect 5', 'Trail Rated', 'Tow Package', 'Apple CarPlay'],
    description: 'Capable Grand Cherokee with 4WD and tow package.',
    imageUrl: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800',
    isAvailable: true,
  },
  {
    year: 2022,
    make: 'Jeep',
    model: 'Wrangler',
    trim: 'Sport',
    price: 38000,
    mileage: 18000,
    bodyStyle: 'SUV',
    seats: 4,
    color: 'Yellow',
    fuelType: 'Gasoline',
    transmission: 'Manual',
    drivetrain: '4WD',
    mpgCity: 17,
    mpgHighway: 23,
    features: ['Removable Top', 'Trail Rated', 'Skid Plates', 'Rock Rails'],
    description: 'Iconic Wrangler Sport with manual transmission.',
    imageUrl: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800',
    isAvailable: true,
  },
  // Volkswagen
  {
    year: 2021,
    make: 'Volkswagen',
    model: 'Tiguan',
    trim: 'SE',
    price: 27000,
    mileage: 32000,
    bodyStyle: 'SUV',
    seats: 7,
    color: 'Gray',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 21,
    mpgHighway: 29,
    features: ['Third Row', 'Panoramic Sunroof', 'Digital Cockpit', 'IQ.DRIVE'],
    description: 'Spacious Tiguan with optional third row.',
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
    isAvailable: true,
  },
  // Lexus
  {
    year: 2021,
    make: 'Lexus',
    model: 'ES',
    trim: 'ES 350',
    price: 42000,
    mileage: 28000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'White',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 22,
    mpgHighway: 32,
    features: ['Mark Levinson Audio', 'Heated/Cooled Seats', 'Navigation', 'Lexus Safety System+'],
    description: 'Refined ES 350 with Mark Levinson premium audio.',
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
    isAvailable: true,
  },
  {
    year: 2020,
    make: 'Lexus',
    model: 'RX',
    trim: 'RX 350',
    price: 45000,
    mileage: 35000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Black',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 20,
    mpgHighway: 27,
    features: ['Premium Package', 'Panoramic View Monitor', 'Wireless Charging', 'Head-Up Display'],
    description: 'Luxurious RX 350 AWD with every option.',
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
    isAvailable: true,
  },
  // Electric vehicles
  {
    year: 2022,
    make: 'Tesla',
    model: 'Model 3',
    trim: 'Long Range',
    price: 45000,
    mileage: 20000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'White',
    fuelType: 'Electric',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 134,
    mpgHighway: 126,
    features: ['Autopilot', 'Premium Interior', 'Glass Roof', 'Supercharging'],
    description: 'Tesla Model 3 Long Range with Autopilot.',
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800',
    isAvailable: true,
  },
  {
    year: 2023,
    make: 'Hyundai',
    model: 'Ioniq 5',
    trim: 'SEL',
    price: 48000,
    mileage: 12000,
    bodyStyle: 'SUV',
    seats: 5,
    color: 'Silver',
    fuelType: 'Electric',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    mpgCity: 110,
    mpgHighway: 87,
    features: ['Vehicle-to-Load', 'Fast Charging', 'Relaxation Seats', 'Augmented Reality HUD'],
    description: 'Award-winning Ioniq 5 with ultra-fast charging.',
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
    isAvailable: true,
  },
  // Budget options
  {
    year: 2018,
    make: 'Chevrolet',
    model: 'Malibu',
    trim: 'LS',
    price: 12500,
    mileage: 78000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Blue',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 27,
    mpgHighway: 36,
    features: ['Bluetooth', 'Backup Camera', 'Teen Driver'],
    description: 'Affordable Malibu with low price point.',
    imageUrl: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800',
    isAvailable: true,
  },
  {
    year: 2017,
    make: 'Ford',
    model: 'Focus',
    trim: 'SE',
    price: 10500,
    mileage: 85000,
    bodyStyle: 'Sedan',
    seats: 5,
    color: 'Red',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 26,
    mpgHighway: 38,
    features: ['SYNC', 'Backup Camera', 'Cruise Control'],
    description: 'Budget-friendly Focus with SYNC connectivity.',
    imageUrl: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800',
    isAvailable: true,
  },
  {
    year: 2016,
    make: 'Toyota',
    model: 'Prius',
    trim: 'Two',
    price: 14000,
    mileage: 92000,
    bodyStyle: 'Hatchback',
    seats: 5,
    color: 'Silver',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    mpgCity: 54,
    mpgHighway: 50,
    features: ['Toyota Safety Sense', 'Backup Camera', 'Climate Control'],
    description: 'Ultra-efficient Prius with amazing fuel economy.',
    imageUrl: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800',
    isAvailable: true,
  },
];

async function seed() {
  const client = postgres(connectionString, { max: 1 });
  const db = drizzle(client);

  console.log('Seeding database...');

  // Clear existing vehicles
  await db.delete(vehicles);

  // Insert sample vehicles
  await db.insert(vehicles).values(sampleVehicles);

  console.log(`Inserted ${sampleVehicles.length} vehicles`);

  await client.end();
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seeding failed:', err);
  process.exit(1);
});
